# -*- coding: utf-8 -*-
"""MediaAluno.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ScQUrJa4bv16c_cwEBrd97F9zBMHzSOJ

Um aluno vai receber três notas de forma dinâmica, por entrada de dados, e se o aluno tirar entre 10 e 7 de média ele será aprovado, senão, se o aluno tirar menos do que 7 e mais do que 4 ele ainda vai para final, senão o aluno reprova automaticamente.
 A sáida de dados deve conter a média do aluno e a sua situação de acordo com a sua média.
"""

n1=float(input('Informe a nota: '))
n2=float(input('Informe a nota: '))
n3=float(input('Informe a nota: '))
media = (n1+n2+n3)/3
if media >= 7:
    sit = 'aprovado'
elif media >=4:
    sit = 'em recuperação'
else:
    sit = 'reprovado'

print(f'O aluno está {sit} com média {media:.2f}')